WebApp_ASP/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp_ASP.Models;

namespace WebApp_ASP.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm] Birth model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }

            //double wynik = model.Calculate();  
            // ViewBag.Result = wynik;  
            return View(model);
        }
    }
}

WebApp_ASP/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp_ASP.Models;
using static WebApp_ASP.Controllers.HomeController;

namespace WebApp_ASP.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public enum Operator
        {
            Unknown, Add, Mul, Sub, Div
        }

        // nasz formularz
        public IActionResult Form()
        {
            return View();
        }

        // PO STWORZENIU MODELU
        //W metodzie wskazano, które dane żądania powinny utworzyć model.
        //Atrybut [FromForm] wskazuje, że model
        //typu Calculator powinien zostać utworzony na podstawie
        //ciała żądania, w którym są dane z formularza
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }

            return View(model);
        }

        // uzywamy modelu wiec to w kontrolerze niepotrzebne
        /*
        public IActionResult Result(Operator op, double? a, double? b)
        {
            double? result = null;

            if (a.HasValue && b.HasValue)
            {
                switch (op)
                {
                    case Operator.Add:
                        result = a + b;
                        break;
                    case Operator.Sub:
                        result = a - b;
                        break;
                    case Operator.Mul:
                        result = a * b;
                        break;
                    case Operator.Div:
                        if (b != 0)
                            result = a / b;
                        break;
                    default:
                        ViewBag.ErrorMessage = "Nieznany operator";
                        break;
                }
            }

            ViewBag.Op = op;
            ViewBag.a = a;
            ViewBag.b = b;
            ViewBag.Result = result;

            return View();
        }
        */
    }
}

WebApp_ASP/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp_ASP.Models;
using WebApp_ASP.Models.Services;

namespace WebApp_ASP.Controllers
{
    public class ContactController : Controller
    {
        //Lista kontaktow

        // musimy korzystac z IContactService,
        // dlatego bo nie definiujemy jak te dane sa przekazywane
        // jesli mbyloby memorycontactservice to ciezko bo trzeba
        // by zmieniac 
        private readonly IContactService _contactService;



        // stworzenie konstruktora 
        // musi zostac wywalony przy tworzeniu instancji kontrolera
        // sprawdza potrzebne parametry, widzi ze potrzebny jest parametr
        // IContactService, sprawdza czy jest taki pracownik
        // ktory implementuje ten interfejs
        // jest jedna taka metoda MemoryContactService
        // ( dziedziczy ona po IContactService)
        // jesli instancji nie ma to sam stworzy i tu przekaze 
        // jesli instancja zostala wczesnien tworzona to przekazuje referencje
        // singleton to jedno zrodlo prawdy
        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }


        public IActionResult Index()
        {
            // przekazanie listy, bardziej uniwersalne
            // ODDZIELENIE LOGIKI PRZETWARZANIA DANYCH OD WYSWIETLANIA
            return View(_contactService.GetAll());
        }

        public IActionResult Delete(int id)
        {
            _contactService.Delete(id);
            // przekierowanie do akcji index
            // index juz wie co przekazac do modelu
            return RedirectToAction(nameof(Index));
            //alternatywa
            //return View("Index", _contactService);
            // return View("Index", contacts);
        }


        public IActionResult Details(int id)
        {
            //W tym miejscu contacts[id] zwraca pojedynczy obiekt
            //ContactModel, który jest przekazywany jako model do widoku.
            return View(_contactService.GetById(id));
        }


        [HttpGet]
        // to wyswietla co edytujemy
        public IActionResult Edit(int id)
        {
            /*
            if (!_contactService.(id))
            {
                return NotFound(); // Zwracamy 404, jeśli kontakt nie istnieje
            }
            */
            // Przekazujemy dane kontaktu do widoku Edit.cshtml
            // to ze tutaj jest contacts[id] powoduje ze basicowo do
            //formularza przekazywane sa dane z id. bez tego bylyby 
            // puste pola bez aktualnych danych
            return View(_contactService.GetById(id));
        }


        [HttpPost]
        // tu juz mozna edytowac 
        public IActionResult Edit(ContactModel model)
        {
            // Sprawdzamy poprawność modelu
            if (!ModelState.IsValid)
            {
                return View(model); // Zwracamy formularz z błędami walidacyjnymi
            }

            /*
            // Sprawdzamy, czy kontakt istnieje
            if (!contacts.ContainsKey(model.Id))
            {
                return NotFound(); // Zwracamy 404, jeśli kontakt nie istnieje
            }
            */

            // Aktualizacja danych kontaktu
            _contactService.Update(model);


            return RedirectToAction(nameof(Index));

            // Powrót do widoku listy kontaktów
            //return View("Index", contacts);
        }

        [HttpGet]

        public IActionResult Add()
        {
            return View();
        }

        // odebranie danyc z formularza, zapis kontaktu i powrot do listy kontaktow
        [HttpPost]
        public IActionResult Add(ContactModel model)
        {
            // jesli model niepoprawny to zwracamy formularz
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // zapisanie danych, powrot do widoku listy

            //return View("Index", contacts);: jawnie określasz,
            //że chcesz użyć widoku "Index"
            //i przekazujesz mu model contacts.

            //PRZENIESIENIE DO MEMORY CONTACTSERVICE
            //model.Id = ++_cureentId;
            // contacts.Add(model.Id, model);


            // logika przeniesiona do memorycontactserive a tam dodawane
            // potem zwracane
            _contactService.Add(model);
            return RedirectToAction(nameof(Index));
        }

        // potrzebujemy znac ostatni id aby dodajac sie nie zdublowal
        private static int _cureentId = 3;


    }
}

WebApp_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp_ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp_ASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp_ASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Calculator" asp-action="Form">Kalkulator</a> <!-- Link do formularza -->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Birth" asp-action="Form">BirthCalculator</a> <!-- Link do formularza -->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApp_ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>